name: PR Merged build (with integration tests)

on:
  push:
    branches:
      - main
      - release/*

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (unit tests)
        run: mvn clean test --no-transfer-progress

      - name: Integration tests
        run: mvn verify -P integration-tests --no-transfer-progress
        env:
          GIGACHAT_API_CLIENT_ID: ${{ secrets.GIGACHAT_API_CLIENT_ID }}
          GIGACHAT_API_CLIENT_SECRET: ${{ secrets.GIGACHAT_API_CLIENT_SECRET }}
          GIGACHAT_API_SCOPE: ${{ secrets.GIGACHAT_API_SCOPE }}
